### ISSUE TITLE
Missing items, etc.

### ISSUE THREAD

**Issue by GreatOrator** [GreatOrator/TolkienCraftII#104]
Reminder,

Forochel skins missing, fast travel to helm's deep still not properly working (why must that guy be so stubborn) and amphel bacon apparently does not want to share the love of his quest

**Comment by GreatOrator** [comment]
Also, esgaroth quest teagan updated

**Comment by teagan75** [comment]
Yes, so all of this is fixed. You will need to update the custom npcs skins folder and quest folder. Also, Forochel and Helms Deep regions need to be updated.

**Comment by GreatOrator** [comment]
Need to fix green dragon branch of scavenger hunt, missing name of inn and drink

**Comment by GreatOrator** [comment]
fixed by teagan.

Update will need to download customNPC folder as well as regions of forochel and Helm's Deep

**Comment by GreatOrator** [comment]
Skins will be taken care of in the next pack update.  Map related issues have been released.
