### ISSUE TITLE
FastCraft causing Clients to Crash

### ISSUE THREAD

**Issue by jelaw21** [GreatOrator/TolkienCraftII#113]
## Description
Clients periodically time-out or crash to desktop. 

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: *server pack from TC II*
* TolkienCraft II version: 2.9.4

## Crash report
```[crash-2016-06-25_05.52.16-client (1).txt](https://github.com/GreatOrator/TolkienCraftII/files/424567/crash-2016-06-25_05.52.16-client.1.txt)
CRASH REPORT HERE
```

**Comment by GreatOrator** [comment]
Are you using the prebuilt maps or a new single player world?  Never seen fastcraft cause a crash...ever before...

**Comment by jelaw21** [comment]
I am using the pre-built maps that accompany the TC2 pack.

**Comment by GreatOrator** [comment]
Not able to recreate this anyway I try.  Try removing it from the pack and see if that helps.

**Comment by jelaw21** [comment]
Pulled it from the pack. Ran then re-added. Worked fine. Weird.
