### ISSUE TITLE
Occulus issues

### ISSUE THREAD

**Issue by timkrieger** [GreatOrator/TolkienCraftII#115]
When wearing any piece of Wyrven armor the content of all the tabs of the AM2 Occulus ( except for Affinity tab ) are not visible.  Removing the Armor and placing it in player inventory makes everything visible again.  Playing on multiplayer server

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 7.99.39.1566
* TolkienCraft II version: 2.9.4
  java 1.8.0.102

**Comment by GreatOrator** [comment]
This is actually an issue to report at the Draconic Evolution github.  However, most development on DE has stopped on version 1.7.10 of minecraft and unfortunately, bug fixing for AM2 has all but been abandoned.
