### ISSUE TITLE
Questbook ussue

### ISSUE THREAD

**Issue by NatchoWorld** [GreatOrator/TolkienCraftII#116]
## Description
Every time i come back to my world it says questmode not enabled and the questbook is clear.
I did the first quests then i logged of a few days later i came back and the questbook was reset (and quest mode disabled).

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1566
* TolkienCraft II version: 2.9.4

## Crash report
```
CRASH REPORT HERE (None)
```

**Comment by teagan75** [comment]
Make sure edit mode is turned off in the config file for HQM

**Comment by NatchoWorld** [comment]
ok ty i will try!!! :D

**Comment by NatchoWorld** [comment]
how can i go to the config screen again?

**Comment by teagan75** [comment]
The config folder is in your .minecraft folder

**Comment by NatchoWorld** [comment]
If it's the last thing it's already off but it still doesn't work

**Comment by GreatOrator** [comment]
The file is simply called editmode.cfg, if it is off (and it should be) are you using a paid minecraft client?  the way HQM works if you are using a cracked client it will not save progress after you log out.

**Comment by NatchoWorld** [comment]
Strange i start a new world and it didn't reset the book..
Ty for Helping!
