### ISSUE TITLE
Client Crashing at Login

### ISSUE THREAD

**Issue by jelaw21** [GreatOrator/TolkienCraftII#117]
## Description
Client crashes when logging in.
## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: TC Server
* TolkienCraft II version: 2.9.4

## Crash report
```
[crash-2016-08-30_11.46.34-client.txt](https://github.com/GreatOrator/TolkienCraftII/files/445966/crash-2016-08-30_11.46.34-client.txt)

CRASH REPORT HERE
```

**Comment by GreatOrator** [comment]
take out optifine and try again
