### ISSUE TITLE
Rohirric Crafting Tables are everywhere

### ISSUE THREAD

**Issue by CreeperCraft97** [GreatOrator/TolkienCraftII#124]
## Description
There are Rohirric Crafting Tables all over the world, underwater, on the floor, everywhere.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: forge-10.13.4.1566
* TolkienCraft II version: 2.9.5

## Crash report
The Rohirric Crafting Tables seem to replace some blocks.
![tcii blocks bug](https://cloud.githubusercontent.com/assets/14940642/19277080/cbab423c-8fd8-11e6-961a-ed764d50eeda.png)

**Comment by GreatOrator** [comment]
Aye, this has been reported multiple times actually, has been reported to the dev of lotr mod as well and he has stated it will not be fixed and unfortunately nothing else I can do.
