### ISSUE TITLE
portal to the void?

### ISSUE THREAD

**Issue by sasdrum** [GreatOrator/TolkienCraftII#128]
## Base information
* Minecraft version: 1.7.10 modded
* Minecraft Forge version: 10.13.4.1566
* TolkienCraft II version: 2.9.5

## there is no crash report. I just die everytime I try to take the portal back to the overworld by falling out of the world.
```

```

**Comment by teagan75** [comment]
You take the actual portal back from ME that is found in Hobbiton or you made your own portal?

**Comment by sasdrum** [comment]
I've tried both the portal that drops you in at the start of the shire, and the portal in hobbiton. I have the same issue on both. I do not have this problem if i'm porting to the milestone in draconis, only when taking the ring portals.


Sent from my Sprint Samsung Galaxy S® 6.
-------- Original message --------From: teagan75 <notifications@github.com> Date: 1/20/17  6:19 PM  (GMT-05:00) To: GreatOrator/TolkienCraftII <TolkienCraftII@noreply.github.com> Cc: sasdrum <silver9tails@gmail.com>, Author <author@noreply.github.com> Subject: Re: [GreatOrator/TolkienCraftII] portal to the void? (#128) 
You take the actual portal back from ME that is found in Hobbiton or you made your own portal?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/GreatOrator/TolkienCraftII","title":"GreatOrator/TolkienCraftII","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/GreatOrator/TolkienCraftII"}},"updates":{"snippets":[{"icon":"PERSON","message":"@teagan75 in #128: You take the actual portal back from ME that is found in Hobbiton or you made your own portal?"}],"action":{"name":"View Issue","url":"https://github.com/GreatOrator/TolkienCraftII/issues/128#issuecomment-274205851"}}}

**Comment by GreatOrator** [comment]
Have you made any changes to the pack or mods?  I just verified that the coordinates are correct in the LOTR.dat file for both entry and exit of middle-earth. Also just installed a fresh copy using the map download and same results.  return to overworld put me in the temple. and going to middle-earth sent me to the pavilion outside of hobbiton.
