### ISSUE TITLE
This crash report the new version TolkienCraft II with FTB launcher, and MultiMC!!

### ISSUE THREAD

**Issue by Sasikaa** [GreatOrator/TolkienCraftII#13]
This crash report with FTB launcher, and MultiMC client:

http://pastebin.com/d8cKJq6b

Somewhere talk
"Something here is messing up ASM. Or two mod's ASM conflicting. No info what does it."

The disabled ASM solved the problem? The ASM in the HQM book?

**Comment by Sasikaa** [comment]
Try disabled ASM and startin up correctly. What mod included the HQM book? I can disable any mods without any problems?

**Comment by GreatOrator** [comment]
Disabling HQM takes a huge chunk of the modpack away.  I would suggest removing the player.dat that is in the harcorequesting folder.  This may reset your quests, but is the most likely cause of the errors.
