### ISSUE TITLE
Server not using Draconis/Middle Earth

### ISSUE THREAD

**Issue by Arkadianwarking** [GreatOrator/TolkienCraftII#130]
Got the server up and running but I load into a void and die only to respawn in an RNG world and not the dock of draconis and the portal to middle earth only takes me to a similer overworld map with random generated design as well. How do I get the server to read the map files I downloaded

## Base information
* Minecraft version: 1.7.2
* Minecraft Forge version:
* TolkienCraft II version: 2.9.5

```

**Comment by GreatOrator** [comment]
Did you download the map?  or the map and content packs from curse?

**Comment by Arkadianwarking** [comment]
Downloaded the map via the in game option, (not the Curse launcher) then copied the Saves folder from the Tolkiencraft 2 folder into the server folder. I'm not certain if this was the right process but i couldn't find directions and it seemed the most straight forward to me

**Comment by GreatOrator** [comment]
You just copy the world folder not the entire saves folder.
