### ISSUE TITLE
 slowmotion bug?  Camera works?

### ISSUE THREAD

**Issue by ytsud1414** [GreatOrator/TolkienCraftII#131]
## Description
when Im on my server and type in chat or open my inventory or any GUI i get this effect like F8 slow motion and it sets a block on the floor called [unnamed block, report to mod author.(#1875)]
its also stops creative fly and zooms in and out?

it usually happens in draconis.
i tried deoping my self oping my self and changing gamemodes and it stil happens every time

i also added a chat mod to my client called IntelliInput that lets me type in japanese with IME but it happens to the other players that dont have it too.

here is a pic of the block is set
https://gyazo.com/faf4bec08a48ab00f4502d3befcf07e0

here is a video of it happening 
https://www.youtube.com/watch?v=je77cYJqK7k&feature=youtu.be

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version:
* TolkienCraft II version:2.9.5

## Server log
PateBin:
[http://pastebin.com/HKwYaVAk](url)

## Server specs 
OS: windows 10pro
Ram: 8G
Java: 8 Update 111 (64 and 32)
 Cpu: i5-4670k

**Comment by ytsud1414** [comment]
i also downloaded the map from the curse site and added all 3 part of the content pack
and using the latest version

i have been to the middle-Earth and DragonBurg

**Comment by ytsud1414** [comment]
update:
it stays slowmotion even when i go to the Middle-Earth (change dementions)
or use the milestone

the only way it stops is typeing in chat

**Comment by ytsud1414** [comment]
i went in to single and the slowmotion effect was still active 
i generated a new world

**Comment by GreatOrator** [comment]
So the slow motion thing is a new one, so don't have an answer for that.  the "block" is a crafting grid placed by one of the mods (i think one of chicken bone's mods) to craft anywhere, anytime.  

Are there any messages in the logs that are spamming when this is happening?

**Comment by ytsud1414** [comment]
there are no messages in the log
it just happens randomly

**Comment by ytsud1414** [comment]
hmm a bug with chicken bones? i guess?

**Comment by ytsud1414** [comment]
could it occur if the RAM and CPU usage is very high?

i had my pc on for 2 or 3 days
and the Ram and cpu usage was 70-90%

**Comment by GreatOrator** [comment]
It very well could, and that particular feature could just be very fps intensive.
