### ISSUE TITLE
Quest issues.

### ISSUE THREAD

**Issue by jamilnielsen** [GreatOrator/TolkienCraftII#132]
## Description
so i have 2 issues.
A: the quest named "Hiring a Merc" seems broken, i've tried it twice, and the sack of coins given by Saruman does not match the required item in the quest it seems. (i have not enchanted or touched the item in any way)
B: Blood magic, Invasion.
this is a two parter, first of all the portal is a problem since the npc's just noped out and walked though it, causing them to never respawn.
and the ritual stopped, could it be possible for future releases to get that ritual "protected"?
## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: not sure, its a server but they know what they're doing.
* TolkienCraft II version: 2.9.5(Curse)

## Crash report
```
CRASH REPORT HERE
```

**Comment by GreatOrator** [comment]
It hasn't stopped, the respawn rate is very slow because of the ME mobs but they do spawn, and the ritual itself has to be constantly loaded to expand.  As for the item, I can take a look, but odd that it broke.

**Comment by jamilnielsen** [comment]
any way to fix the respawn rate? i killed about a few Hundred orcs, trolls, etc with only One grunt hiding under a house(i later used an Xray mod to double check if i simply missed them to be safe)

**Comment by GreatOrator** [comment]
unfortunately no, it is coded in bloodmagic

**Comment by jamilnielsen** [comment]
then perhaps in future it should be moved to a place or dimension were it does not get disrupted :)

**Comment by teagan75** [comment]
the problem with that is the ritual produces a ton of lag so if it were chunk loaded all the time it would be problematic for some people and servers

**Comment by jamilnielsen** [comment]
sure, but having an insane amount of orcs, trolls, etc spawn(to the very limit of what said server allows) really don't help much.
the amount and speed of them is simply that fast.
i'll attach a picture if i can.

**Comment by jamilnielsen** [comment]
by the way, is there a way to reset individual player's questting with the customnpc quests?, noticed deleteing player.dat don't solve it.

**Comment by GreatOrator** [comment]
You have to be in creative mode and right click on any npc and the advanced tab you can do it there

It is saved in a json file in the world folder iirc.
