### ISSUE TITLE
Whoo! My download's -1.83943156E10% done! (Possible floating point number overflow in map downloader)

### ISSUE THREAD

**Issue by aytimothy** [GreatOrator/TolkienCraftII#134]
## Description
I just installed the pack brand new and on installing the map, well... This happened.

[![Well, this happened](https://puu.sh/uwrVH/2af21d2c3b.png)](https://puu.sh/uwrVH/2af21d2c3b.png)

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1566
* TolkienCraft II version: 2.9.5

## Crash report
No crash report to log.

There appears to be nothing logged in relation to the map download.

**Comment by GreatOrator** [comment]
Hmmm, that's a new one.  I'll have to test later today when at home.  in the mean time you can still download the main map and all content packs from curse so you can still get to playing :D

**Comment by GreatOrator** [comment]
So potentially was an issue with the download link.  It "should" be handled now (I can't reproduce it anyways) going to close but feel free to reopen if there is still an issue.
