### ISSUE TITLE
Chunks not loading

### ISSUE THREAD

**Issue by Myndbew** [GreatOrator/TolkienCraftII#137]
![2018-05-13_18 08 51](https://user-images.githubusercontent.com/39248539/39972837-cf353c1c-56e4-11e8-81d8-259bb67f2c9f.png)
Description: I opened up my Tolkiencraft II world, and I was greeted with a large chunk that wasn't loaded in. I waited a few minutes, thinking it would pass. It didn't. I'd appreciate it if you could help!

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 1.7.10
* TolkienCraft II version: 1.7.10

## Crash report
```
CRASH REPORT HERE
```

**Comment by Myndbew** [comment]
![2018-05-13_18 08 51](https://user-images.githubusercontent.com/39248539/39972407-fe9891d2-56dc-11e8-839a-03ae233e5096.png)
Here's a screenshot

**Comment by Myndbew** [comment]
![2018-05-13_18 08 51](https://user-images.githubusercontent.com/39248539/39972499-5d25120a-56df-11e8-988e-a83997033e40.png)
Here's a screenshot

**Comment by GreatOrator** [comment]
Was that an area you built in or one of the pregenned areas?  if it is pregenned, simply redownload the map to replace the corrupted chunk (if it is truly gone) if it is an area you built in, sadly there is not much that can be done.

**Comment by Myndbew** [comment]
Alright thanks

**Comment by Myndbew** [comment]
wait, if I redownload the map, won't I reset everything I've built?
