### ISSUE TITLE
Detected ongoing potential memory leak. 300 packets have leaked. Top offenders

### ISSUE THREAD

**Issue by Sasikaa** [GreatOrator/TolkienCraftII#14]
This crash with approx. 1 hour game:

http://pastebin.com/YzKS82Bw

The crash report is not generated, this report cutting my fml-client-latest.log file!!
The game is run VERY LAGGY, fastcraft and optinfine installed (optifine 3-4 version testing, and lagg...) My game is run 4gb ram. (my system 6gb!)

RPGadvmod is buggy?

**Comment by GreatOrator** [comment]
I have reported that memory leak to the mod developer awhile ago, not sure if or when he will fix it.  Main issue is it does not show up in every map.

**Comment by Sasikaa** [comment]
If disabled this mod (RPGadvmod) what happen the modpack?
