### ISSUE TITLE
If disabled this mod (RPGadvmod) what happen the modpack?

### ISSUE THREAD

**Issue by Sasikaa** [GreatOrator/TolkienCraftII#15]
If disabled this mod (RPGadvmod) what happen the modpack?

(memory leak crash!)

**Comment by teagan75** [comment]
If you disable RPG Adv mod you will not have any of the waypoint signs in the town showing POI

**Comment by teagan75** [comment]
So if it's between HQM and RPG Adv, choose the latter.

**Comment by Sasikaa** [comment]
What? HQM is this pack is needed! The HQM is way across this modpack? Or not?

**Comment by Sasikaa** [comment]
And, enabled ASM and the modpack is not loading... Sound Engine freeze... The optifine is not compatible this mod?

**Comment by GreatOrator** [comment]
If you are using optifine, that would also be the cause of your memory leak.  Unfortunately you will have to reach out to the optifine dev to make sure he is 100% compatible with forge version 1448.
