### ISSUE TITLE
How do i Exactley Remove Items from the Pack?

### ISSUE THREAD

**Issue by Daphonic** [GreatOrator/TolkienCraftII#16]
# add the unlocalized name of a block or item to this list to disable it [default: ]
    S:"Disabled Blocks & Items" <
     >

this part? I want to Remove
Draconic Staff of Power
Dezil's Marshmallow

**Comment by Daphonic** [comment]
# add the unlocalized name of a block or item to this list to disable it [default: ]
    S:"Disabled Blocks & Items" <
		DraconicEvolution:dezilsMarshmallow
		DraconicEvolution:draconicDistructionStaff
     >

I did this after a bit of Googleing. But they still show up.

**Comment by GreatOrator** [comment]
That is not what that function is for.  The marshmallow is only available if your name is dezil or you cheat it in and the staff of power is the main end game component of DE.

As for as removing or disabling, sorry I do not help with removal of items or mods from my pack as they are all there for a reason.

**Comment by Daphonic** [comment]
Understood, the Marshmallow's were showing up in Chests. Wanted to limit the staff for server lag reasons.
