### ISSUE TITLE
2 Kings and queens

### ISSUE THREAD

**Issue by ttimo123456** [GreatOrator/TolkienCraftII#17]
Just started playing TolkienCraft II and when I got to the king there were 2 of him and 2 queens, and for some reason after I did touring city quest I didn't get the next quest, If I was suppose to.
If someone could explain this that would be great.

**Comment by teagan75** [comment]
Custom NPCs sometimes duplicates the NPCs. You can remove them with the NPC wand. 

To get the quest, you need to let the two NPCs by the fountain finish their conversation. Hit L to see if you have a quest.

**Comment by teagan75** [comment]
Sorry misread the name of the quest. Talk to the king to get the bandit quest.

**Comment by ttimo123456** [comment]
Thanks It helped me out a lot!
