### ISSUE TITLE
Quest problem

### ISSUE THREAD

**Issue by zSuitSamus** [GreatOrator/TolkienCraftII#18]
Hello!
I just finished a quest line for Chald. Now I have a quest to go see the mages council. But it requires me to have a Council Summons. I didn't receive an item from Chald when I picked up the quest (like the Queen's Note for instance) and there doesn't seem to be any quest going along with the Council Summons in the quest book. I've tried a few tricks suggested by other players, such as renaming an item on an anvil to say "Council Summons", but it didn't work. I'm at a loss. 

Thanks for the awesome pack btw, it's been a lot of fun so far... and pretty difficult.

**Comment by GreatOrator** [comment]
Did you check your email?  and what version of the pack are you on?

Glad you are enjoying it :)

**Comment by zSuitSamus** [comment]
Checking the mail box was the last thing I tried before I decided to contact you guys. I thought maybe Chald mailed it to me, it's happened before. Both my boyfriend and I are having the same problem. We are using version 2.7.2 through the FTB client. (we have had an issue before where we didn't receive a quest book at the start. We simply created a new server... but since we're so far into the game now, we'll do that as a last resort)

**Comment by GreatOrator** [comment]
I'll double check when I get home later, but if i recall, there should be mail for that quest.  what happens when you talk to chald?

As a side note, have plans on a rework of some of the key HQM components to not only help even more keeping on track for quests, but to implement a new job board feature.  So part of that work will be re-verifying/correcting/modifying the existing quests and potentially adding some new ones :)

**Comment by zSuitSamus** [comment]
When I talk to Chald, he tells me his story about the mages guild contacting him and then asks if I could go. Then of course I have the quest in the log. I don't know how difficult it would be, but an abandon quest option may help. *shrugs* 

Always look forward to more quests and an easier way to track them :D Would those updates require us to make a new server?

**Comment by zSuitSamus** [comment]
Oh! Off topic, I want to let you know that I had died in a protected zone and my gravestone spawned in it. Couldn't break it of course. Eventually I was able to break the gravestone (for some reason spam clicking an un-breakable block in creative mode broke the protection? lol).

**Comment by GreatOrator** [comment]
Yeah, the protected area issue is the lesser of two evils.  No easy way to keep it from being ransacked though I have seen that turning keep inventory on bypasses the graves and avoids those issues in those areas.

As for the abandon quest, no easy way, though you can go into creative, grab an npc wand and remove that quest so you have to accept it and do it over.

**Comment by zSuitSamus** [comment]
I'll have to look into that bypass for the grave issue and we'll try using an NPC wand to see if it fixes the bug. I'll let you know.

**Comment by zSuitSamus** [comment]
Update! We tried removing and starting the quest again. We didn't get any mail from chald. So... we ended up having to replace the Council Summons with bread, lol. Also, the chain quest after you speak to Malus was bugged. My boyfriend had to reset it twice and then "fixed" something in them for the quest line to continue. What was happening was, we would finish talking to the troll but the next quest wouldn't show up in our log. I would have to have my boyfriend tell you exactly what he had to fix with the NPC wand. But after he did his "fix" we got the next quest in line after speaking to the troll. (seems we got unlucky with having quest issues)

**Comment by GreatOrator** [comment]
I am actually working in my dev environment today, will double check something did not accidentally break on the quests (would not be the first time)

**Comment by GreatOrator** [comment]
Something else I forgot to ask, if this is on a server, do you have command blocks enabled?

**Comment by GreatOrator** [comment]
So have gone through, after defeating the troll, did you receive mail that gave you a piece of paper called troll death and then did you take that and complete with the king?

**Comment by zSuitSamus** [comment]
Oh, the troll thing is after the fact. When Chald asks you to talk to the mage council. You figure out that your enemies were actually being controlled. The point where you talk to the troll, the quest never picked back up like it did after you spoke to the witch.

**Comment by zSuitSamus** [comment]
And about the command blocks thing, I have no clue lol, neither does the boyfriend. So I'm guessing we don't, if it's disabled by default.

**Comment by GreatOrator** [comment]
So the death of a troll leads you to ahab, and also a quest opens to talk to the barkeep.  did you get that far?

**Comment by GreatOrator** [comment]
and yes, command blocks are off on servers by default

**Comment by zSuitSamus** [comment]
We're currently at the point were we will be joining the bloodmage guild in Wyvernhaven

**Comment by zSuitSamus** [comment]
The part of the quests that didn't picked up automatically was Mage Council I, you talk to Elphaba and it says she wasn't helpful. Then you get Mage Council II to talk to Tyltran, that's the quest that wouldn't pop into my quest log.

**Comment by GreatOrator** [comment]
So I assume you found out what was wrong with getting the mage council quest?  Will be continuing shortly one the rest of the main quest line.  So far haven't found anything broken, though I have made changes to be more in line with the new Job Board changes

**Comment by zSuitSamus** [comment]
Okay, asked BF what he did to fix the quest line Mage Council I-IV. He said that after MC II, the quest line wasn't tied to III and the same thing with III to IV. So he used the wand to "tie" them together. After that, we repeated I and we finally got the update in the quest log that we received quest II. I'm wondering if we're having issues because we downloaded our server through Feed The Beast.

**Comment by teagan75** [comment]
That part of the questline has always been a little hokey...no offense GreatOrator!!! :) The confusing part comes when it auto completes and says the witch wasn't helpful when in fact you havent even talked to her. To pick up the troll quest or MCII you have to talk to Ephelba and so on with the others as well.

**Comment by GreatOrator** [comment]
Ok, so taking a look, I do need to adjust the location where the quest completes.  the quest don't link directly, you get each consecutive one as you complete the dialogs from them

**Comment by GreatOrator** [comment]
Alright, so found nothing broken, what I did do however was to modify the locations a bit and the completion text so rather than it reading like you finished, you are going in to talk, should eliminate the confusion

**Comment by zSuitSamus** [comment]
OH! That's what the problem was! We weren't going in to talk to the npc's since we got that dialogue lol

**Comment by zSuitSamus** [comment]
I think I have one last question. When you are asked to join the blood mages guild in Wyvernhaven, you are supposed to talk to Bethany to start the quest line. The iron door that blocks the way, are we supposed to put a lever beside the door to get in or are we missing something?

**Comment by GreatOrator** [comment]
The door should open automatically after the quest registers, it did for me in my let's play.  Just read the quest text to make sure you are on the right path.
