### ISSUE TITLE
Draconic Evolution Tablet menu is too large for Auto GUI

### ISSUE THREAD

**Issue by KaleWesker** [GreatOrator/TolkienCraftII#22]
When you right click with the Draconic Evolution Tablet, the menu that pops up is too large to fit on the screen while Minecraft's GUI is set to Auto. I had to change my GUI to a reduced size.
![draconic evolution tablet screenshot 1](https://cloud.githubusercontent.com/assets/14833511/10095851/264e9ac8-63b0-11e5-8ced-f20241416146.jpg)
![draconic evolution tablet screenshot 2](https://cloud.githubusercontent.com/assets/14833511/10095852/264f5cce-63b0-11e5-95d3-74cc733d6a39.jpg)
I hate playing with any GUI smaller than "Large" (which the Auto size on my game). Smaller GUIs are harder to read and the items shown on the right with NEI are harder to identify in this state.

Just reduce the tablet height and split the index into two pages. Alternatively, and this may even be better, you could have the entire index on one wider page, listing the items in 2 columns.

The tablet in it's current state (v1.0.1c for MC 1.7.10) is borderline unacceptable. When Tinkers' Construct manuals amongst other manuals from other mods are already setting excellent examples of how information should be presented, there's just no excuse for a manual that cannot be navigated without messing with the games GUI options.

**Comment by GreatOrator** [comment]
This has already been reported to the mod dev, and as much as I would love to be in a position to fix, this would be better served at the mods issues github than here
