### ISSUE TITLE
Quest problem

### ISSUE THREAD

**Issue by damiontech** [GreatOrator/TolkienCraftII#26]
ok me and a few friend are having issues with killing the coven leader in the witch cave her name is Ephalba

**Comment by GreatOrator** [comment]
Explain problem.  That is too open ended an explanation.

**Comment by zSuitSamus** [comment]
I think I've had the same problem with the update. She's not aggressive and you cannot attack her. We had to change her settings to aggressive with the NPC wand to complete the quest.

**Comment by GreatOrator** [comment]
That's not the problem, I guarantee it.  You simply go talk to elm to fix your faction standing, then go back to the captain and run through the dialog again.  She's not attacking because your faction level is too high.
