### ISSUE TITLE
Elm's options don't seem to do anything

### ISSUE THREAD

**Issue by MidnightSin** [GreatOrator/TolkienCraftII#27]
I've tried talking to Elm to get a new Quest Book or to fix my faction standing with Villain (Friendly: 2000 / --  at the moment) but neither option seems to do anything. Am I missing a config on the server?

**Comment by GreatOrator** [comment]
Do you have command blocks enabled on the server?

**Comment by MidnightSin** [comment]
If it's enabled by default, then yes. Otherwise, which config file has it?

**Comment by GreatOrator** [comment]
Check server properties, and no it is not enabled by default.

**Comment by MidnightSin** [comment]
Just checked and it was disabled, restarting server right now.

**Comment by MidnightSin** [comment]
That did it, thanks GO. :D
