### ISSUE TITLE
Blood Magic: Tier 2

### ISSUE THREAD

**Issue by MidnightSin** [GreatOrator/TolkienCraftII#29]
The quest requires the player to make 2 items: Apprentice Blood Orb (Altar Tier 2) and Ritual Diviner (Altar Tier 3) but the player only has access to the Apprentice Workshop (Altar Tier 2). Are we supposed to make an altar of our own (Tier 3) to move on with the questline?

**Comment by GreatOrator** [comment]
Would you be able to make it if you didn't make your own?  The idea for the ones in-town was to help get you started, not to replace making your own.

**Comment by MidnightSin** [comment]
Unlike the Tier 1 and Tier 3 quests, Tier 2 forces you to make your own, there doesn't seem to be another way around the Ritual Diviner (other than Tier 6 recipe)

**Comment by teagan75** [comment]
I did overlook that you can't make the inscription items for the diviner on the a tier 2 altar. I will have to change that for the update.
