### ISSUE TITLE
I made a boo boo

### ISSUE THREAD

**Issue by damiontech** [GreatOrator/TolkienCraftII#32]
I was doing the quest in the investigation part and I broke the dirt but I was in creative not paying attention how do I repair the block so my other friends can finish the quest so I dont have to spawn them the items

**Comment by GreatOrator** [comment]
unfortunately it is not dirt but a HQM quest block, fortunately it will not impact quest completion as it just simply hides the hole, so everyone else will be able to complete the quest still.
