### ISSUE TITLE
 Bug: Incorrect cords

### ISSUE THREAD

**Issue by zSuitSamus** [GreatOrator/TolkienCraftII#33]
Gandalf's location for the quest book is 0,0,0 in the dimension that Draconis is in. This is only for the part where you report to him after you give the ring to Bilbo and then read the mail. Attached a photo for reference.

![family-heirloom-reporting](https://cloud.githubusercontent.com/assets/14186548/10408966/625d5576-6ed3-11e5-8fc3-36d7a1d30d98.png)

**Comment by GreatOrator** [comment]
Yes, like most of the other stuff, the hqm was a side effect of pushng a mod update out, there are several quests that were unfinished :)
