### ISSUE TITLE
v2.9.0 - Mirkwood and the Rise of Angmar

### ISSUE THREAD

**Issue by GreatOrator** [GreatOrator/TolkienCraftII#35]
Setting this up for future use, will update this issue as we get closer.

Figured a checklist of sorts was in order to finalize when we are close to a release.

Stuff to do:
- [x] Job Boards for new locations
- [x] Fast Travel for new locations
- [x] HQM
- [x] Thranduil's Halls
- [x] Blue Mountains/Nogrod
- [x] Old Man Willow
- [x] Carn Dum (Angmar)
- [x] Grey Havens
- [x] New Quest functions (Aragorn, Beorn, etc)
- [x] New NPC shops

**Comment by GreatOrator** [comment]
Added HQM fixes for major update as they potentially could affect the quest book

**Comment by Bornzombieman27** [comment]
I think the quest Inn of the prancing pony is broken because the the Xyz are X - 14245 Y - 91 Z - 794
Please Fix

**Comment by GreatOrator** [comment]
Fixed radius of location point on Prancing Pony.

**Comment by GreatOrator** [comment]
Will begin detail work such as Job Boards this week hopefully
