### ISSUE TITLE
2.8.1 Hobbiton - Ruined crop quest

### ISSUE THREAD

**Issue by valsnoisytoys** [GreatOrator/TolkienCraftII#42]
Not sure if this is intended or not, but the fella asks for potato seeds and he accepts wheat seeds in their place to complete the quest.

**Comment by GreatOrator** [comment]
will double check, but may simply be an issue with meta data so may not be anything we can do to change that.

**Comment by teagan75** [comment]
I completed that last night and he took potato seeds.

**Comment by teagan75** [comment]
checked this quest. It is asking for potato seeds so if it takes wheat seeds instead, I have no way to prevent that.

**Comment by GreatOrator** [comment]
Yeah, I think in this case there is not much we can do, but thank you for pointing it out.  :D
