### ISSUE TITLE
2.8.1 Hobbiton - Too Many Orders quest

### ISSUE THREAD

**Issue by valsnoisytoys** [GreatOrator/TolkienCraftII#43]
Holly completes the quest, but doesn't take away the strawberry pies. Also unsure what she gives in return - didn't notice specifically how many coins I had before, but I also didn't notice any new items either after turning it in.

**Comment by GreatOrator** [comment]
Tomorrow is check all the bugs day :)

**Comment by teagan75** [comment]
Did you get a new quest to deliver the pies? If you delivered them already she only takes half the coins you got from the customers and leaves you with the rest.

**Comment by teagan75** [comment]
I have fixed this quest.
