### ISSUE TITLE
two broken quests

### ISSUE THREAD

**Issue by azaziel** [GreatOrator/TolkienCraftII#47]
I believe I've found two broken quests:

1) in middle earth, in an inn in the Shire you get a quest from the barkeep to find a wagon. Well I've found it and it does not update the quest.. nor is there any info on the text page of the quest.

2) in HQM down the Quest Journal path, once you get to choosing a side to go to : good or bad... the quest doesn't tell you HOW or WHERE to get the token you need to turn in. besides cheating and pulling this from NEI which is impossible on a server... the quest book should tell you. or give you the tokens as reward. something. anything to continue questing. ty

**Comment by teagan75** [comment]
The broken quest in Hobbiton should be fixed in an update soon. The tokens are given as a reward for continuing down one of the paths with the NPCs. The HQM book is there to record certain milestones while completing NPC quests.

**Comment by azaziel** [comment]
TY. do you know if there is a place I can go to for Quest Help? now I cannot find Headmaster Attallia where ever I look. :/

**Comment by teagan75** [comment]
All headmasters are near the altars they are "testing"

**Comment by azaziel** [comment]
ive looked that headmaster isnt anywhere in any of the rooms. ive only seen headmaster johnathan

**Comment by teagan75** [comment]
She is in the apprentice room. Head in the door and turn left. If not it could be a missing NPC. I am not sure if that NPC is saved as a clone so 1. You can go into creative and grab the custom NPC clone wand use it and see if the NPC is on the list or 2. Re-download the map.

**Comment by azaziel** [comment]
im playing on a multi-server. its not a single world lol. but ill mention it to the server owner if i still cant find her ty

**Comment by azaziel** [comment]
OMG she was hiding in the corner of the room where i couldn't see her... dear lord. head desk

**Comment by azaziel** [comment]
okay now i have got the quest the Council Summons. but its not updating when i go up the tower. ive spoek o the mages numerous tiems and even done their quests. adid i do it out of rder or something?

**Comment by GreatOrator** [comment]
did you get the piece of paper to take there?  which quest specifically in customNPC's is listed, have you asked anyone on the server if they had the same issue?

**Comment by azaziel** [comment]
yes i did. no NPC is specifically listed. just to take the summosn to the top of the mages council. which i did

**Comment by GreatOrator** [comment]
Well, maybe there, tested locally and on my whitelisted server and the quest works fine, the location block is the one right under the top floor and was fixed a long time ago and testing just finished it is still working.  About a dozen people on my WL server have completed it as well, I would reach out to your server admin to see what may have changed on your server.
