### ISSUE TITLE
Rendering Block Entity

### ISSUE THREAD

**Issue by AeroyrHwrdd** [GreatOrator/TolkienCraftII#48]
Having a few strange mod interactions on my multiplayer server. I've seen the Blood Altar act strange with something in the Gravestone's mod at some point and more recently LOTRs' mod armor stand crashing when rendering Clothing Mod items. Just thought I'd bring it to attention. I'm okay for server fixes myself. :)

**Comment by GreatOrator** [comment]
Thank you, will research, though I know of a number of mods that are not happy with lotr armor stands unfortunately
