### ISSUE TITLE
quest reinforcements

### ISSUE THREAD

**Issue by theaphexhanna** [GreatOrator/TolkienCraftII#49]
I just started this pack and Im trying to do the quest reinforcements where you are to go into the sewers and place reinforcements. I was not given the items to place though and cannot find them in NEI to "cheat " in. any solution ideas?

**Comment by GreatOrator** [comment]
Are you doing the customNPC quests as well?  that is where you get the items, text in HQM even mentions it

There will be a fix for HQM coming soon though(TM)

**Comment by theaphexhanna** [comment]
I am yes. it is possible Ive missed an npc somewhere though. will go through them all again. thanks

**Comment by GreatOrator** [comment]
Malus is the NPC that gives them to you
