### ISSUE TITLE
Can't open questbook in multiplayer anymore

### ISSUE THREAD

**Issue by Sazra** [GreatOrator/TolkienCraftII#56]
I opened a little mp server for me and my friends but since the update i can't open the questbook anymore, i tried making a new world with the map, but even then nothing happens when i try to open the book.

I don't know if this is an problem with the pack or with HQM, so I reported the issue here first

**Comment by GreatOrator** [comment]
Check your server log to see if anything shows up in there, just tested myself and the book is opening just fine.  What version did you upgrade from?

**Comment by teagan75** [comment]
Did you try typing /hqm quest

**Comment by Sazra** [comment]
yeah the quests were active
I upgraded from 2.8.1 to 2.8.3 of the pack

**Comment by GreatOrator** [comment]
try uploading the hqmquest.dat in the configs to the server is the only thing I can think of at this point, can't replicate this issue unfortunately

**Comment by Sazra** [comment]
well, that fíxed the issue -.-
i didnt think about this type of solution
