### ISSUE TITLE
Nei Recipe Bug

### ISSUE THREAD

**Issue by Algurt** [GreatOrator/TolkienCraftII#63]
Not sure If I should be putting this here, but I didnt really know where to put this other than here.

Hosting my own private server off my pc just for me and my friends, but whenever I try and find the recipe for an item, our games just kinda crash. 

Pastebin Server log: http://pastebin.com/REBmDVQ4

**Comment by GreatOrator** [comment]
Please try reading the closed issues, I am aware and next update should have that fixed, on the ftb forum I posted a work-around.
