### ISSUE TITLE
Question about sword swing delay

### ISSUE THREAD

**Issue by RagingPickle** [GreatOrator/TolkienCraftII#66]
I've been searching around for what's been causing a delay in sword swing speed. Turns out it's from the LoTR mod. While I like its added dynamic, the people I have on a private server dislike it and wish for me to disable it as it's causing unwanted death. I've checked the configs but that's led me nowhere. Is there any way to do so? If not, will there ever be?

**Comment by GreatOrator** [comment]
Currently there is no way to disable it and does not look like mevans has plans to add that anytime soon.  Honestly though, I have it on my whitelisted server and it has encouraged players to find alternative ways to fight such as more reliance on potions and such
