### ISSUE TITLE
Crash upon launching Optional Tolkiencraft Middle-Earth Map

### ISSUE THREAD

**Issue by Shad0wS3th** [GreatOrator/TolkienCraftII#72]
[crash-2016-03-06_12.54.47-server.txt](https://github.com/GreatOrator/TolkienCraftII/files/160516/crash-2016-03-06_12.54.47-server.txt)

I don't really know if I'm posting this correctly, but I'm having an issue when i try to run the Middle earth map. I get to the part to where I can choose to play a world or create a new one but when i try to play on the map the game just crashes. any support would be greatly appreciated, but I installed Optifine and was experiencing issues with it so i removed it. I've been really wanting to play this map as i have seen playthroughs and videos about it but i cant seem to get it to work for the life of me.

**Comment by GreatOrator** [comment]
what version of the pack and are you using the latest map download? Only thing in that crash log that could possibly be the issue is you are on java 7 and there are a bunch of mods that now run on java 8

**Comment by Shad0wS3th** [comment]
Sorry for such the late response. it seemed to work when I got back on, i
have no clue how restarting a computer could do that but ive been playing
it for 3 days now and i have to say its so dang fun and i can see myself
sinking many more hours into it.


This email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by GreatOrator** [comment]
Glad to hear it!
