### ISSUE TITLE
TPS Drop / Server Lockup When Nearby Players after 2.8.8 Map update

### ISSUE THREAD

**Issue by Bluesnarf** [GreatOrator/TolkienCraftII#73]
There is an issue that I have noticed that after the map update be it in version 2.8.7 or 2.8.8 that when I get too close to other players or other players get too close to each other, the server will lock up and spam the console with "Can't keep up messages" until they are at least 10-15 blocks a part. Unfortunately, I cannot get the server to completely crash to get a crash-report and that is all that is presented in the logs. This causes a server load average spike and at times, disconnects all players from the server. Is there anything I can provide to assist in troubleshooting this issue?

Also, this issue was not present on Draconis map template v2.8.x RC7.

**Comment by GreatOrator** [comment]
I will check later today, but have not seen this issue (or noticed anyways) on my whitelisted server.  Are you using only forge or kcauldron as well? I know of another server (the one in the server list) that recently updated and did not have that issue.

**Comment by Bluesnarf** [comment]
I currently am only using forge. I am using v2.8.7 of the modpack as soulbound enchant is working properly in that version and the bleed effect bug isn't there. Eventually the server just died after the upgrade, nobody as able to connect without being disconnected 10s after. After I deployed v2.8.7 and the latest map the latter stopped but the issue with the player proximity disconnects reoccured.

**Comment by GreatOrator** [comment]
So there were a few changes to mods between 2.8.7 and 2.8.8, if this was a fresh start for you guys, try uploading a fresh copy of the map and see if the issue persists and let me know

**Comment by Bluesnarf** [comment]
This actually is a fresh copy of the map, I deleted the server iteration that had the issues in v2.8.8 and did not downgrade. So currently the server is a fresh v2.8.7 of the modpack with the latest map template RC9 and expansion including RC2 for Middle earth part 2.

**Comment by GreatOrator** [comment]
Try these, they are the versions of the map before the 2.8.8 update.  I gave the full path since they are not normally accessible otherwise

http://minecraft.curseforge.com/projects/tolkiencraft-ii-draconis/files/2275831/download

http://minecraft.curseforge.com/projects/tolkiencraft-ii-content-pack/files/2263449/download
http://minecraft.curseforge.com/projects/tolkiencraft-ii-content-pack/files/2263448/download

**Comment by Bluesnarf** [comment]
These appear to be dead links. Is a Curse account required to view them?

**Comment by GreatOrator** [comment]
really? when I click on them they download, so maybe you do?

**Comment by Bluesnarf** [comment]
Yeah, I just logged in with my Curse account, still "We were unable to find the page or file you were looking for.". Perhaps permissions?

**Comment by Bluesnarf** [comment]
Looks like it was my playerdata. I deleted everything with my UUID and IGN and that resolved the issue. Last time this happened I also displayed the alcoholic shield. I'm going to do a restore on my server and do some more testing to see if i can find the root cause.

**Comment by Bluesnarf** [comment]
Do you by chance have a list of playerdata .dat files that contain LOTR metadata?

**Comment by GreatOrator** [comment]
as far as I am aware it is stored in the normal player.dat files

**Comment by Bluesnarf** [comment]
Ok, because I deleted the selected shield from the playerdata in ./world/LOTR/UUID.dat and when I log back in it re-populates the tag with the selected shield. Does anything else append that file or is anything read from other playerdata that would cause it to reselect that shield and append the tag?

**Comment by GreatOrator** [comment]
hmmm, that is a good one, will have to look

**Comment by Bluesnarf** [comment]
Did some more testing, removed all general achievements from my LOTR data which allowed me to remove the title/shield. I went and re-tested with another player, the issue still persists so it is not related to the shield.

**Comment by Bluesnarf** [comment]
So I found the issue after extensive testing. Apparently, the issue occurs when there is too much or too many items in your customnpc's bank account. My bank size on the local disk was 132kb, average size of a player on the server is 10kb. After deleting that data and retesting the issue was no longer present. I am not sure why this occurs but it may be something for the mod author to look into.

The general path to this player data files is as follows:

./world/customnpcs/playerdata/PLAYER-UUID.json

**Comment by GreatOrator** [comment]
Thank you for all of that, I will let noppes know about it, though not sure if that is something that he will fix since he has moved on to 1.8.x.
