### ISSUE TITLE
Thaumcraft golems with the core "use" do not interact with the world as they should

### ISSUE THREAD

**Issue by Bluesnarf** [GreatOrator/TolkienCraftII#74]
Tolkiencraft 2 Version 2.8.7

Issue description:
Thaumcraft golems with the core "use" do not interact with the world as they should. If assigned to a chest with saplings and instructed to plant the saplings, they will grab the sapling out of the chest, walk over to the block where they are instructed to plant the sapling and simply stand there holding a sapling.

The issue is not limited to saplings, but also prevents the golems from interacting with any interactable block, including blocks specifically designed for golem "use" core.

Strangely, this can only be reproduced when the server hosts the game, while in single player the golem has no trouble interacting with the same objects. 

additional notes:
- Issue is not limited to any specific golem type. 
- The issue appears to be limited to just the "use" core, though not much experimentation has been done with others. 
- The issue is not limited to any dimension or area - this can be reproduced anywhere. 

Repro steps:
1) give yourself the following items:
/give <self> 515 1 (grindstone from AE2)
/give <self> 2341 (Thaumic Energistics' thaumium gear box)
/give <self> 6629 1 (straw golem)
/give <self> 6588 1 8 (golem "use" core)
/give <self> 6663 1 (golemancer's bell)
/give <self> 406 64 (stack of quartz)

2) Place the grindstone on the ground, and put the stack of quartz into the grindstone
3) place the thaumium gear box on top of the grindstone
4) right click on the thaumium gear box using your straw golem to deploy it. You may want to raise the ground beside the grindstone so that the golem is on the same level as the gear box
5) right click on the golem with the use core
6) right click on the golem with the golemancer's bell, and right click again on the side of the thaumium gear box beside which he is deployed.
7) watch the derp stare at the gear box like a dunce.

Are there any steps that can be taken to resolve this issue?

**Comment by GreatOrator** [comment]
I have seen this sporadically, usually if a server has some sort of protection plugin, however, it has been reported to azanor, but sadly will probably go unfixed as he has solidly moved to minecraft 1.8.9.  there are actually several use/right click functions that will spam a server console that I have reported.

Thank you though for confirming.
