### ISSUE TITLE
Hostile mob spawners spawn mobs, which then disappear.

### ISSUE THREAD

**Issue by adamvan2000** [GreatOrator/TolkienCraftII#77]
Tolkiencraft 2 Version 2.8.9

Issue description: All the mob spawners for creepers, skeletons, and zombies spawn mobs, which disappear almost right away. Also, no hostile mobs are spawning anywhere outside of the city.

additional notes:
I am attaching my log, just in case there's something useful in them.
[fml-client-latest.txt](https://github.com/GreatOrator/TolkienCraftII/files/193201/fml-client-latest.txt)

Repro steps:
N/A
Are there any steps that can be taken to resolve this issue?
N/A

**Comment by GreatOrator** [comment]
Have you checked to make sure you are set to normal difficulty?  sounds like your game somehow switched to peaceful

**Comment by adamvan2000** [comment]
Sure enough, I was. Thanks for the help! :D
