### ISSUE TITLE
Draconic Chest - lost inventory

### ISSUE THREAD

**Issue by Kotawolf** [GreatOrator/TolkienCraftII#78]
Discovered this today, and duplicated the issue.

If player is holding the chest when server restart happens, then the inventory in the chest is wiped out.
Lost everything that was in it, somewhat annoying, but I can recover that stuff easily enough.

**Comment by brandon3055** [comment]
Was it a regular restart or a crash?

**Comment by Kotawolf** [comment]
Regular restart

**Comment by brandon3055** [comment]
Ok so i was not able to reproduce that issue. Are you running any server managers such as cauldron?

**Comment by Kotawolf** [comment]
Nope,  built what I'm running via Curse.    Since you can't reproduce, it has to be something else causing a conflict.  I can try and figure out what mod it is, but will take time.

**Comment by GreatOrator** [comment]
so was this in the tolkiecraft modpack or a custom pack?

**Comment by Kotawolf** [comment]
Mod list:
<ul>
<li><a href="http://minecraft.curseforge.com/mc-mods/227983">MFR Magical Crops Compatibility (by Portablejim)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/220333">CoFHLib (by TeamCoFH)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/60089">Mouse Tweaks (by YaLTeR97)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/237102">FTB Utilities  (by FTB)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/228756">Iron Chests (by progwml6)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/233140">Buildcraft Compat (by buildcraftchildsplay)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/73488">Waila (by ProfMobius)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/232134">SimpleLabels (by insaneau)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/237103">FTB Tweaks (by FTB)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/229876">BetterFps (by Guichaguri)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/230368">Block Properties (by docrobb)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/67504">ComputerCraft (by dantwohundred)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/77191">AnimationAPI (by thehippomaster21)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/70496">BdLib (by bdew)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/223794">Applied Energistics 2 (by AlgorithmX2)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/221585">Roguelike Dungeons (by Greymerk)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/237167">FTBLib (by FTB)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/32274">JourneyMap (by techbrew)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/62121">InfiniBows (Infinity Bow Fix) (by Myrathi)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/67313">Ars Magica 2 (by Torarion)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/236203">Ender IO Addons (by Henry_Loenwind)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/221913">Pam's Clay Spawn (by MatrexsVigil)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/229306">Ender Storage (by chicken_bones)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/224614">NotEnoughKeys (by dmodoomsirius)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/60092">Aroma1997s Dimensional World (by Aroma1997)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/222213">CodeChickenCore (by chicken_bones)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/64578">Ender IO (by CrazyPants_MC)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/69163">Thermal Expansion (by TeamCoFH)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/225605">LunatriusCore (by Lunatrius)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/229318">Translocators (by chicken_bones)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/224942">Dense Ores (by RWTema)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/224029">MineTweaker3 (by StanH)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/223896">MalisisCore (by Ordinastie)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/69118">Morpheus (by quetzi)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/224728">FloodLights (by Keridos)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/229218">ExtraCells2 (by DrummerMC)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/63352">NEI Addons (by bdew)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/70635">Obsidian Boat (by zilulil)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/227443">Thermal Dynamics (by TeamCoFH)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/239262">Too Many Ores (by AKTheKnightMC)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/59769">ObsidiPlates (by Myrathi)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/61811">Buildcraft (by CovertJaguar)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/227878">Minecraft Minions (by AtomicStryker)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/225815">NotEnoughResources (by Way2muchnoise)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/228834">Magical Crops (by Mark719)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/236204">Waterhook (by Henry_Loenwind)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/233105">McJtyLib (by McJty)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/225604">InGame Info XML (by Lunatrius)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/223094">Inventory Tweaks (by Kobata)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/225194">AE2 Stuff (by bdew)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/226797">Magical Crops Compat - Minefactory Reloaded (by Streuner91)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/221863">Another One Bites the Dust (by ganymedes01)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/222880">Thermal Foundation (by TeamCoFH)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/66672">Minefactory Reloaded (by skyboy026)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/225251">NEI Integration (by tonius111)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/69162">CoFH Core (by TeamCoFH)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/66675">NetherOres (by skyboy026)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/243205">Mo' Villages (by The_WeatherPony)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/223735">Aroma1997Core (by Aroma1997)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/222211">NotEnoughItems (by chicken_bones)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/225561">Extra Utilities (by RWTema)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/238474">EnderOre (by adcrafter27)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/223815">In-Game Wiki Mod (by MineMaarten)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/59216">Treecapitator (by bspkrs)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/241994">Big Reactors (by ErogenousBeef)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/74924">Mantle (by mDiyo)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/51195">Railcraft (by CovertJaguar)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/223548">Solar Flux (by Nauktis)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/227564">OreDictionaryConverter (by EXTER7)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/220954">ModTweaker (by jaredlll08)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/79325">Simply Jetpacks (by tonius111)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/225063">Adventure Backpack (by JavierDarkona)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/224712">Wawla - What Are We Looking At (by darkh4x)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/228609">QuantumFlux (by jotato)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/59413">Enchanting Plus (by darkh4x)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/221910">Pam's Weee! Flowers (by MatrexsVigil)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/223428">EnderTech (by voxelcarrot)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/226410">ProjectE (by sinkillerj)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/79287">Waila Harvestability (by squeek502)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/225635">AgriCraft (by InfinityRaider)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/223583">Solar Expansion (by TedTheRusSB624)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/78886">FlatBedrock Xplosion's Edition (by big_Xplosion)</a></li>
<li><a href="http://minecraft.curseforge.com/mc-mods/231853">Equivalent Energistics (by Mordenkainen3141)</a></li>
</ul>

**Comment by Kotawolf** [comment]
Completely Custom pack.

**Comment by brandon3055** [comment]
Then you probably should have posted in on the DE github. Not the Tolkiencraft pack github...

**Comment by Kotawolf** [comment]
Oh crap.. sorry guys.

**Comment by Kotawolf** [comment]
Closing, cause I'm apparently not paying enough attention.
