### ISSUE TITLE
kekimurus promblem

### ISSUE THREAD

**Issue by killmetohell** [GreatOrator/TolkienCraftII#79]
I have problem Some unknown reason the kekimurus is not eating the cake i place i even replaced it use of creative that is the cake to see the cake was problem and it wasn't so was wondering if guys did anything in mod pack that maybe or could have disable kekimurus that is if you guys did this on purpose or not i post this problem already on botania but been some time after i posted no solution yet so i thought might post here as well.

**Comment by GreatOrator** [comment]
What version of the pack?  I know there was an issue way back when, but have used the cake method myself since with no issues.  Is this single player or multiplayer and if multiplayer what plugins are being used? (some plugins require special perms as they would be considered a user)

**Comment by killmetohell** [comment]
the pack version is 2.89 other than that a few mods i updated my self but that it and its single player.

**Comment by GreatOrator** [comment]
i will tst locally myself to see what happens and let you know...may be broken and if it is vazkii probably won't fix it...sigh

**Comment by killmetohell** [comment]
i hope it isn't thought don't expect it be broken for some unknown reason unless some weird reason her code got messed up causing it not to work.

**Comment by killmetohell** [comment]
i made a test world with only a few mod it seems kekimurus is working fine there. So must something with the mods maybe?
All in saying the only thing i can think that can effect it is something that would effect cakes.

**Comment by GreatOrator** [comment]
That's possible, but the food mods in the pack have barely changed.  So far in single player it has been working for me so not sure what would cause this yet.

**Comment by killmetohell** [comment]
I'll try to see if replacing the cake again would work then try making a new world to see if there any differents  from it once I get back home. 

    On Wednesday, April 20, 2016 8:29 AM, GreatOrator <notifications@github.com> wrote:
 

 That's possible, but the food mods in the pack have barely changed. So far in single player it has been working for me so not sure what would cause this yet.—

**Comment by killmetohell** [comment]
Me either i,ll try later to see if i try replacing it again work and trying a new world as well once i get back home.

Sent from my Samsung device

-------- Original message --------

**Comment by killmetohell** [comment]
GreatOrator commented 8 hours ago

That's possible, but the food mods in the pack have barely changed. So far in single player it has been working for me so not sure what would cause this yet.

I just thought a bit reading ue message i might reading it bit to much but if meant that recipes changes or meant by changing food it self well might be like saying reading bit to much into it.

**Comment by killmetohell** [comment]
Found something Interesting apparently i think all my pam's harvestcraft cakes work but minecraft cake or lotr cakes don't work weird.

**Comment by GreatOrator** [comment]
Heh, well at least there are cakes that can be made to work with it i guess.  Not sure what is happening since I still have not replicated in my test environment.  Since there is a work-around if anyone else does report this I will close this for now and point anyone else to this issue if it comes up.
