### ISSUE TITLE
Server Crash- Aquatic Abyss Repeatedly crashing the server

### ISSUE THREAD

**Issue by ProsperCraft** [GreatOrator/TolkienCraftII#8]
in 2.7.0 and 2.7.1

http://pastebin.com/tHcB8MZX

Reported here-
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2151604-aquatic-abyss-swordfish-and-serpents-v1-1-1?comment=461

**Comment by teagan75** [comment]
You are running the modpack with Cauldron. This is not happening on Forge servers. Have you asked the Cauldron guys about a fix?

**Comment by ProsperCraft** [comment]
Everyone is so quick to blame KCauldron...

Here, from the Aquatic Abyss thread-

http://pastebin.com/raw.php?i=CjTgurtf

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2151604-aquatic-abyss-swordfish-and-serpents-v1-1-1?comment=450

**Comment by teagan75** [comment]
All of the recent reported crashes on the Aquatic Abyss forum thread indicate KCauldron is being used.

**Comment by ProsperCraft** [comment]
Good call, reported here - https://gitlab.prok.pw/Prototik/KCauldron/issues/159
