### ISSUE TITLE
Cant go to #2

### ISSUE THREAD

**Issue by Hamp14** [GreatOrator/TolkienCraftII#80]
I finished #1 and it wont let me go onto #2. What do i do? It says its locked.

**Comment by GreatOrator** [comment]
#1 what and #2 what?

**Comment by GreatOrator** [comment]
Closing since no response

**Comment by Hamp14** [comment]
Chapter 2 of the quest book. Sorry it took a while for the responce.

**Comment by GreatOrator** [comment]
In order to open section 2 you have to get the paper and key from the queen, if you have, try dropping it on the ground and picking it back up

**Comment by Hamp14** [comment]
Oh okay, thank you so much!
