### ISSUE TITLE
Glitch in Draconis

### ISSUE THREAD

**Issue by Nekofy** [GreatOrator/TolkienCraftII#81]
I've been playing the tolkiencraft modpack for a while now and untill now i had no issues. a while back i had to start over (new laptop and forgot backups) and so i had to start over some of the first quest. at some point you have the quest in wich you have to kill this troll. no matter what i do, it's incvincible in my game. i can't hit it and it ignores me. i even managed to push it in the fire, but the fire didn't hurt it. i'll attach the screenshot i made of the troll on fire. but i hope i can eighter get around the quest, of there's a way to solve the invincebility because this rederns me unable to continue the line of quests.
![2016-04-25_22 15 38](https://cloud.githubusercontent.com/assets/18685182/14827976/2703ffca-0be5-11e6-8955-a1cb3cfd63d9.png)
already big thanks for taking the time reading this.

**Comment by GreatOrator** [comment]
First the FAQ is a wonderful thing!

Second, talk to elmn on the docks, he can fix the faction for you.  if that does not work, are you on a server?  if so, make sure command blocks are enabled.

Make sure you are also on the quest to kill him (customnpc quest not HQM)

**Comment by Nekofy** [comment]
i have talked to elmn, it didn't work, i am playing single, and i have the quest active. guess i'll have to delete my world and start over again?

**Comment by GreatOrator** [comment]
No, you won't have to restart the world (unless you want to) but if he truly can not be hit by you (he is immune to all but hand held weapons) there is something you missed in the quests.  He has a very weird hit box because he is so large.  fire, arrows, etc won't work on purpose, only swords

**Comment by Nekofy** [comment]
I'm trying to hit him with my swords, nothing works, and he actually ignores me. so i think it might be a glithc that happened with my own game. so i'll jsut redownload the map an start over. hopefully it'll solve this. thx for taking your time to read my post and reply.
Ps. i really love the modpack, great work.
