### ISSUE TITLE
Cosmetic Armor - Can't view cosmetic inventory

### ISSUE THREAD

**Issue by valsnoisytoys** [GreatOrator/TolkienCraftII#82]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2287519-cosmetic-armor-v1-0-5-because-its-important-to-be

Hey GO! :)

Not sure if this is a conflict with another mod, but you're supposed to be able to press C and have the Cosmetic inventory come up so you can equip skin armor (effectively armor that allows your skin to be visible instead of whatever armor you're wearing).  

However, C, even when unmapped from other uses listed in the controls config screen (eg Draconic Evolution) doesn't bring up this inventory, nor could I find a way to open it via the tabs above the E inventory screen.
It also isn't listed in the control config screen, so you can't remap it to something else to try that.
Either I'm missing something (always possible) or there is an issue.

**Comment by GreatOrator** [comment]
Alright, so double checked, I have the key mapped by default to numpad 4 and it opens up fine.  Let me know if that wrks for you or if I have to check on other things.

**Comment by valsnoisytoys** [comment]
Ah! Yes Numpad 4 works. Thanks!
