### ISSUE TITLE
Planting Issues

### ISSUE THREAD

**Issue by gldebroeck1** [GreatOrator/TolkienCraftII#87]
So, I created a GitHub account just so I can ask this question. I have looked all over the internet and in various forums. I play a TolkienCraft 2 in Single player, and I generated a world of my own, which turned out especially lovely. But I am having problems being able to plant things. Like I use a hoe or a mattock to turn dirt or grass into farmland but I cannot put the seeds in the ground. There is also plenty of water in the area and the farmland darkens to signify it is wet. Sorry if someone answered this question already, it just seems the mod has a ton of really awesome stuff for farming and I'd like to be able to do that. Thanks!

**Comment by GreatOrator** [comment]
Easy enough, this pack uses agricraft and the ability to plant is limited to using crop sticks is all.
