### ISSUE TITLE
Drawbridge Dupilaction

### ISSUE THREAD

**Issue by rdemay91** [GreatOrator/TolkienCraftII#88]
## Description
duplication of items with a storage drawers drawer with packing tape on it, items inside. puting the container in a drawbridge and apply redstone signal with dupe items each time you activate drawbridge. similar to drawbridge in 1.6.4. recommend adding all the containers to blacklist in tinkers mechworks config. similar to strongbox. 

## Base information
* Minecraft version:1.7.10
* Minecraft Forge version:10.134.4.1614
* TolkienCraft II version:2.8.10

## Crash report
```
CRASH REPORT HERE
```

**Comment by GreatOrator** [comment]
Will take a look, though to be honest balance was never an over-arching theme in the pack :D, still though will look into it.  Thank you for bringing it to my attention.

**Comment by GreatOrator** [comment]
Alright, was easy enough, will be in the next update release.
