### ISSUE TITLE
recipe conflict making circuit plates (projectred core)

### ISSUE THREAD

**Issue by syvy** [GreatOrator/TolkienCraftII#90]
Cannot make Projectred core: circuit plate (6453)
recipe makes lotr mod: scorched stone (3122) instead
tested in furnace and redstone furnace.

**Comment by GreatOrator** [comment]
What version of TolkienCraft are you playing?  I will double check, but I had disabled the scorched stone recipe for just that reason.

**Comment by syvy** [comment]
I was playing multiplayer and didn't work.  but just tested on client single player 2.8.10 and recipe works.  

Likely I forgot to copy something over to the server and a random version mismatch somewhere on my end...

**Comment by GreatOrator** [comment]
Yeah, check the configs, sounds like a file for the recipe manager did not get copied over

**Comment by syvy** [comment]
nevermind,  was all me.  zcrafting mod was missing for some reason but the config was fine, lol
