### ISSUE TITLE
missing block in blood altar in wyverhaven

### ISSUE THREAD

**Issue by ZeroLyfe** [GreatOrator/TolkienCraftII#98]
## Description 
One on the glowstone blocks is missing from the blood altar in the archmages workshop under wyverhaven making it a tier 2 altar instead of a tier 5. checked on a new download of the map version 2.9.2 .
## Base information
* Minecraft version:
* Minecraft Forge version:
* TolkienCraft II version:2.9.2

**Comment by GreatOrator** [comment]
Thank you, will check and fix.

**Comment by GreatOrator** [comment]
Should be fixed in the latest map update available on curse
